version: '3'
services:
  dotnet:
    build: ./docker/dotnet
    tty: true
    ports:
      - 9012:5000
    volumes:
      - .:/application
    depends_on:
      - db

  db:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
